# Generated by Django 2.0.2 on 2018-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BinaryField()),
                ('testChar', models.PositiveIntegerField()),
                ('testCC', models.CharField(max_length=100)),
            ],
        ),
    ]
