# Generated by Django 2.0.2 on 2018-05-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('options', models.TextField()),
                ('key', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeData', models.BinaryField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FillInBlankQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('blankKeys', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('options', models.TextField()),
                ('keys', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PairQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('leftOptions', models.TextField()),
                ('rightOptions', models.TextField()),
                ('pairKeys', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('options', models.TextField()),
                ('keys', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sectionID', models.CharField(max_length=32)),
                ('flag', models.PositiveSmallIntegerField()),
                ('star', models.PositiveSmallIntegerField()),
                ('Key', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
