# Generated by Django 2.0.2 on 2018-05-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseFunApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fillinblankquestion',
            old_name='blankKeys',
            new_name='blankKey',
        ),
        migrations.RenameField(
            model_name='multichoicequestion',
            old_name='keys',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='pairquestion',
            old_name='pairKeys',
            new_name='pairKey',
        ),
        migrations.RenameField(
            model_name='sortquestion',
            old_name='keys',
            new_name='key',
        ),
    ]
