# Generated by Django 2.1.2 on 2018-12-27 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseFunApp', '0003_auto_20181227_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsetting',
            name='unlock_number',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 21, 22, 56, 92945)),
        ),
        migrations.AlterField(
            model_name='notices',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 21, 22, 56, 91948)),
        ),
        migrations.AlterField(
            model_name='notices',
            name='publicDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 21, 22, 56, 90950)),
        ),
    ]
