# Generated by Django 2.0.2 on 2018-05-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 19, 18, 5, 396960)),
        ),
        migrations.AlterField(
            model_name='notices',
            name='publicDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 19, 18, 5, 396960)),
        ),
    ]
