# Generated by Django 2.0.2 on 2018-05-10 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0002_auto_20180510_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 20, 9, 28, 465525)),
        ),
        migrations.AlterField(
            model_name='notices',
            name='publicDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 20, 9, 28, 465525)),
        ),
    ]
