# Generated by Django 2.0.2 on 2018-05-28 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0005_auto_20180514_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='expireDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 21, 53, 1, 843893)),
        ),
        migrations.AlterField(
            model_name='notices',
            name='publicDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 21, 53, 1, 843893)),
        ),
    ]
